name: Build and publish storybook

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages-${{ github.ref_name }}"  # unique builds for branch/tag name
  cancel-in-progress: true

jobs:
  storybook:
    name: Create storybook build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Build Storybook docs
        run: |
          yarn install
          yarn build:storybook

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./storybook-static

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Exclude PRs
    needs: storybook
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  chromatic:
    name: Visual regression test with Chromatic
    runs-on: ubuntu-latest
    needs:
      - storybook

    if: "${{ secrets.CHROMATIC_PROJECT_TOKEN }}" != ""

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: github-pages
          path: ./storybook-static

      - name: Publish to Chromatic for visual regression tests
        uses: chromaui/action@v1
        if: github.event.pull_request.draft == false
        with:
          autoAcceptChanges: main
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: ./storybook-static
